# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jade Abbott
description: "Jade Abbott, Founder, NLP Researcher, Speaker"
keywords: "Jade Abbott, NLP, African Languages, Masakhane"
url: https://jabbott.io
baseurl: ""

google_analytics: UA-52446115-1
repo: https://github.com/jaderabbit/jaderabbit.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jade Abbott
  job: Founder, NLP Researcher, Speaker
  bio: "Director @ Lelapa AI. NLP for African Languages @ Masakhane. Bassist @ FMFY"
  thumb: /images/me.jpg
  email: jade.zoe.abbott@gmail.com
  url: https://jabbott.io
  github: https://github.com/jaderabbit
  twitter: https://twitter.com/alienelf
  linkedin: https://www.linkedin.com/in/jade-abbott-5b3a692a/

# navbar pages
navbar:
  - slug: about
    title: whoami();
  - slug: blog
    title: read();
  - slug: talks
    title: watch();
  - slug: research
    title: research();


exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
